#!/bin/bash

echo "This script will help you add design files to Xcode."
echo ""
echo "IMPORTANT: You need to do this IN XCODE manually:"
echo ""
echo "1. Right-click 'Countdown2Binge' folder in Xcode"
echo "2. Choose 'Add Files to Countdown2Binge...'"
echo "3. Navigate to: Countdown2Binge/Screens/"
echo "4. Select ALL these files:"
echo "   - DesignSystem.swift"
echo "   - CoreComponents.swift"
echo "   - TabBarView.swift"
echo "   - TimelineScreen.swift"
echo "   - BingeReadyScreen.swift"
echo "   - DiscoverSearchScreen.swift"
echo "   - OnboardingFlow.swift"
echo ""
echo "5. Make sure 'Countdown2Binge' target IS checked ✅"
echo "6. Make sure 'Copy items if needed' is UNCHECKED ❌"
echo "7. Click 'Add'"
echo ""
echo "Then press Cmd+B to build."
